<?php
/**
 * GetTokenResponseModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * GetTokenResponseModel Class Doc Comment
 *
 * @category    Class
 * @description Provides details of a token.
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetTokenResponseModel implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'string',
        'payer' => 'string',
        'email_address' => 'string',
        'attribute_values' => '\Swagger\Client\Model\AttributeValueModel[]',
        'transaction_type' => 'string',
        'masked_account_number' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'payer' => 'payer',
        'email_address' => 'emailAddress',
        'attribute_values' => 'attributeValues',
        'transaction_type' => 'transactionType',
        'masked_account_number' => 'maskedAccountNumber'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'payer' => 'setPayer',
        'email_address' => 'setEmailAddress',
        'attribute_values' => 'setAttributeValues',
        'transaction_type' => 'setTransactionType',
        'masked_account_number' => 'setMaskedAccountNumber'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'payer' => 'getPayer',
        'email_address' => 'getEmailAddress',
        'attribute_values' => 'getAttributeValues',
        'transaction_type' => 'getTransactionType',
        'masked_account_number' => 'getMaskedAccountNumber'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id The unique identifier of the token.
      * @var string
      */
    protected $id;
    
    /**
      * $payer The name of the payer.
      * @var string
      */
    protected $payer;
    
    /**
      * $email_address The email address of the payer.
      * @var string
      */
    protected $email_address;
    
    /**
      * $attribute_values A collection of key/value pairs for any custom attribute values for this token.
      * @var \Swagger\Client\Model\AttributeValueModel[]
      */
    protected $attribute_values;
    
    /**
      * $transaction_type The type of transaction.
      * @var string
      */
    protected $transaction_type;
    
    /**
      * $masked_account_number The masked account number for display to the user.
      * @var string
      */
    protected $masked_account_number;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->id = $data["id"];
            $this->payer = $data["payer"];
            $this->email_address = $data["email_address"];
            $this->attribute_values = $data["attribute_values"];
            $this->transaction_type = $data["transaction_type"];
            $this->masked_account_number = $data["masked_account_number"];
        }
    }
    
    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param string $id The unique identifier of the token.
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets payer
     * @return string
     */
    public function getPayer()
    {
        return $this->payer;
    }
  
    /**
     * Sets payer
     * @param string $payer The name of the payer.
     * @return $this
     */
    public function setPayer($payer)
    {
        
        $this->payer = $payer;
        return $this;
    }
    
    /**
     * Gets email_address
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->email_address;
    }
  
    /**
     * Sets email_address
     * @param string $email_address The email address of the payer.
     * @return $this
     */
    public function setEmailAddress($email_address)
    {
        
        $this->email_address = $email_address;
        return $this;
    }
    
    /**
     * Gets attribute_values
     * @return \Swagger\Client\Model\AttributeValueModel[]
     */
    public function getAttributeValues()
    {
        return $this->attribute_values;
    }
  
    /**
     * Sets attribute_values
     * @param \Swagger\Client\Model\AttributeValueModel[] $attribute_values A collection of key/value pairs for any custom attribute values for this token.
     * @return $this
     */
    public function setAttributeValues($attribute_values)
    {
        
        $this->attribute_values = $attribute_values;
        return $this;
    }
    
    /**
     * Gets transaction_type
     * @return string
     */
    public function getTransactionType()
    {
        return $this->transaction_type;
    }
  
    /**
     * Sets transaction_type
     * @param string $transaction_type The type of transaction.
     * @return $this
     */
    public function setTransactionType($transaction_type)
    {
        $allowed_values = array("Ach", "Visa", "MasterCard", "Discover", "AmericanExpress", "Jcb");
        if (!in_array($transaction_type, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'transaction_type', must be one of 'Ach', 'Visa', 'MasterCard', 'Discover', 'AmericanExpress', 'Jcb'");
        }
        $this->transaction_type = $transaction_type;
        return $this;
    }
    
    /**
     * Gets masked_account_number
     * @return string
     */
    public function getMaskedAccountNumber()
    {
        return $this->masked_account_number;
    }
  
    /**
     * Sets masked_account_number
     * @param string $masked_account_number The masked account number for display to the user.
     * @return $this
     */
    public function setMaskedAccountNumber($masked_account_number)
    {
        
        $this->masked_account_number = $masked_account_number;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
