<?php
/**
 * PostPaymentPageSessionRequestModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * PostPaymentPageSessionRequestModel Class Doc Comment
 *
 * @category    Class
 * @description Represents the information needed to customize a single transaction via the payment page.
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostPaymentPageSessionRequestModel implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'attribute_values' => 'map[string,string]',
        'amount' => 'double',
        'comments' => 'string',
        'initiating_party_credit_card_fee' => 'double',
        'initiating_party_ach_fee' => 'double',
        'success_url' => 'string',
        'payer_fee' => 'double',
        'accepted_payment_methods' => 'string[]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'attribute_values' => 'attributeValues',
        'amount' => 'amount',
        'comments' => 'comments',
        'initiating_party_credit_card_fee' => 'initiatingPartyCreditCardFee',
        'initiating_party_ach_fee' => 'initiatingPartyAchFee',
        'success_url' => 'successUrl',
        'payer_fee' => 'payerFee',
        'accepted_payment_methods' => 'acceptedPaymentMethods'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'attribute_values' => 'setAttributeValues',
        'amount' => 'setAmount',
        'comments' => 'setComments',
        'initiating_party_credit_card_fee' => 'setInitiatingPartyCreditCardFee',
        'initiating_party_ach_fee' => 'setInitiatingPartyAchFee',
        'success_url' => 'setSuccessUrl',
        'payer_fee' => 'setPayerFee',
        'accepted_payment_methods' => 'setAcceptedPaymentMethods'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'attribute_values' => 'getAttributeValues',
        'amount' => 'getAmount',
        'comments' => 'getComments',
        'initiating_party_credit_card_fee' => 'getInitiatingPartyCreditCardFee',
        'initiating_party_ach_fee' => 'getInitiatingPartyAchFee',
        'success_url' => 'getSuccessUrl',
        'payer_fee' => 'getPayerFee',
        'accepted_payment_methods' => 'getAcceptedPaymentMethods'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $attribute_values Key/value collection of all custom attributes that will eventually be stored with the transaction.
      * @var map[string,string]
      */
    protected $attribute_values;
    
    /**
      * $amount The total amount of the transaction inclusive of all fees.
      * @var double
      */
    protected $amount;
    
    /**
      * $comments Used to pre-populate the comments section of the payment page.
      * @var string
      */
    protected $comments;
    
    /**
      * $initiating_party_credit_card_fee The fee to keep for the initiating party of this transaction in the event of a credit card transaction. This does not include transaction fees.
      * @var double
      */
    protected $initiating_party_credit_card_fee;
    
    /**
      * $initiating_party_ach_fee The fee to keep for the initiating party of this transaction in the event of an ACH transaction. This does not include transaction fees.
      * @var double
      */
    protected $initiating_party_ach_fee;
    
    /**
      * $success_url The Url to which the user will be redirected upon a successful payment.
      * @var string
      */
    protected $success_url;
    
    /**
      * $payer_fee The fee the payer is paying. This is not additive to the Amount field.
      * @var double
      */
    protected $payer_fee;
    
    /**
      * $accepted_payment_methods A white-list of accepted payment methods that should be shown on the payment page.
      * @var string[]
      */
    protected $accepted_payment_methods;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->attribute_values = $data["attribute_values"];
            $this->amount = $data["amount"];
            $this->comments = $data["comments"];
            $this->initiating_party_credit_card_fee = $data["initiating_party_credit_card_fee"];
            $this->initiating_party_ach_fee = $data["initiating_party_ach_fee"];
            $this->success_url = $data["success_url"];
            $this->payer_fee = $data["payer_fee"];
            $this->accepted_payment_methods = $data["accepted_payment_methods"];
        }
    }
    
    /**
     * Gets attribute_values
     * @return map[string,string]
     */
    public function getAttributeValues()
    {
        return $this->attribute_values;
    }
  
    /**
     * Sets attribute_values
     * @param map[string,string] $attribute_values Key/value collection of all custom attributes that will eventually be stored with the transaction.
     * @return $this
     */
    public function setAttributeValues($attribute_values)
    {
        
        $this->attribute_values = $attribute_values;
        return $this;
    }
    
    /**
     * Gets amount
     * @return double
     */
    public function getAmount()
    {
        return $this->amount;
    }
  
    /**
     * Sets amount
     * @param double $amount The total amount of the transaction inclusive of all fees.
     * @return $this
     */
    public function setAmount($amount)
    {
        
        $this->amount = $amount;
        return $this;
    }
    
    /**
     * Gets comments
     * @return string
     */
    public function getComments()
    {
        return $this->comments;
    }
  
    /**
     * Sets comments
     * @param string $comments Used to pre-populate the comments section of the payment page.
     * @return $this
     */
    public function setComments($comments)
    {
        
        $this->comments = $comments;
        return $this;
    }
    
    /**
     * Gets initiating_party_credit_card_fee
     * @return double
     */
    public function getInitiatingPartyCreditCardFee()
    {
        return $this->initiating_party_credit_card_fee;
    }
  
    /**
     * Sets initiating_party_credit_card_fee
     * @param double $initiating_party_credit_card_fee The fee to keep for the initiating party of this transaction in the event of a credit card transaction. This does not include transaction fees.
     * @return $this
     */
    public function setInitiatingPartyCreditCardFee($initiating_party_credit_card_fee)
    {
        
        $this->initiating_party_credit_card_fee = $initiating_party_credit_card_fee;
        return $this;
    }
    
    /**
     * Gets initiating_party_ach_fee
     * @return double
     */
    public function getInitiatingPartyAchFee()
    {
        return $this->initiating_party_ach_fee;
    }
  
    /**
     * Sets initiating_party_ach_fee
     * @param double $initiating_party_ach_fee The fee to keep for the initiating party of this transaction in the event of an ACH transaction. This does not include transaction fees.
     * @return $this
     */
    public function setInitiatingPartyAchFee($initiating_party_ach_fee)
    {
        
        $this->initiating_party_ach_fee = $initiating_party_ach_fee;
        return $this;
    }
    
    /**
     * Gets success_url
     * @return string
     */
    public function getSuccessUrl()
    {
        return $this->success_url;
    }
  
    /**
     * Sets success_url
     * @param string $success_url The Url to which the user will be redirected upon a successful payment.
     * @return $this
     */
    public function setSuccessUrl($success_url)
    {
        
        $this->success_url = $success_url;
        return $this;
    }
    
    /**
     * Gets payer_fee
     * @return double
     */
    public function getPayerFee()
    {
        return $this->payer_fee;
    }
  
    /**
     * Sets payer_fee
     * @param double $payer_fee The fee the payer is paying. This is not additive to the Amount field.
     * @return $this
     */
    public function setPayerFee($payer_fee)
    {
        
        $this->payer_fee = $payer_fee;
        return $this;
    }
    
    /**
     * Gets accepted_payment_methods
     * @return string[]
     */
    public function getAcceptedPaymentMethods()
    {
        return $this->accepted_payment_methods;
    }
  
    /**
     * Sets accepted_payment_methods
     * @param string[] $accepted_payment_methods A white-list of accepted payment methods that should be shown on the payment page.
     * @return $this
     */
    public function setAcceptedPaymentMethods($accepted_payment_methods)
    {
        
        $this->accepted_payment_methods = $accepted_payment_methods;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
