<?php
/**
 * PostTransactionFeesResponseModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * PostTransactionFeesResponseModel Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostTransactionFeesResponseModel implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'ach_payer_fee' => 'double',
        'credit_card_payer_fee' => 'double'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'ach_payer_fee' => 'achPayerFee',
        'credit_card_payer_fee' => 'creditCardPayerFee'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'ach_payer_fee' => 'setAchPayerFee',
        'credit_card_payer_fee' => 'setCreditCardPayerFee'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'ach_payer_fee' => 'getAchPayerFee',
        'credit_card_payer_fee' => 'getCreditCardPayerFee'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $ach_payer_fee 
      * @var double
      */
    protected $ach_payer_fee;
    
    /**
      * $credit_card_payer_fee 
      * @var double
      */
    protected $credit_card_payer_fee;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->ach_payer_fee = $data["ach_payer_fee"];
            $this->credit_card_payer_fee = $data["credit_card_payer_fee"];
        }
    }
    
    /**
     * Gets ach_payer_fee
     * @return double
     */
    public function getAchPayerFee()
    {
        return $this->ach_payer_fee;
    }
  
    /**
     * Sets ach_payer_fee
     * @param double $ach_payer_fee 
     * @return $this
     */
    public function setAchPayerFee($ach_payer_fee)
    {
        
        $this->ach_payer_fee = $ach_payer_fee;
        return $this;
    }
    
    /**
     * Gets credit_card_payer_fee
     * @return double
     */
    public function getCreditCardPayerFee()
    {
        return $this->credit_card_payer_fee;
    }
  
    /**
     * Sets credit_card_payer_fee
     * @param double $credit_card_payer_fee 
     * @return $this
     */
    public function setCreditCardPayerFee($credit_card_payer_fee)
    {
        
        $this->credit_card_payer_fee = $credit_card_payer_fee;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
