<?php
/**
 * PreAuthorizationModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * PreAuthorizationModel Class Doc Comment
 *
 * @category    Class
 * @description Contains information for offline pre-authorizations.
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PreAuthorizationModel implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'pre_authorization_code' => 'string',
        'pre_authorization_date' => '\DateTime'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'pre_authorization_code' => 'preAuthorizationCode',
        'pre_authorization_date' => 'preAuthorizationDate'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'pre_authorization_code' => 'setPreAuthorizationCode',
        'pre_authorization_date' => 'setPreAuthorizationDate'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'pre_authorization_code' => 'getPreAuthorizationCode',
        'pre_authorization_date' => 'getPreAuthorizationDate'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $pre_authorization_code The pre-authorization code created by the issuing bank.
      * @var string
      */
    protected $pre_authorization_code;
    
    /**
      * $pre_authorization_date The date issuance of the pre-authorization code.
      * @var \DateTime
      */
    protected $pre_authorization_date;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->pre_authorization_code = $data["pre_authorization_code"];
            $this->pre_authorization_date = $data["pre_authorization_date"];
        }
    }
    
    /**
     * Gets pre_authorization_code
     * @return string
     */
    public function getPreAuthorizationCode()
    {
        return $this->pre_authorization_code;
    }
  
    /**
     * Sets pre_authorization_code
     * @param string $pre_authorization_code The pre-authorization code created by the issuing bank.
     * @return $this
     */
    public function setPreAuthorizationCode($pre_authorization_code)
    {
        
        $this->pre_authorization_code = $pre_authorization_code;
        return $this;
    }
    
    /**
     * Gets pre_authorization_date
     * @return \DateTime
     */
    public function getPreAuthorizationDate()
    {
        return $this->pre_authorization_date;
    }
  
    /**
     * Sets pre_authorization_date
     * @param \DateTime $pre_authorization_date The date issuance of the pre-authorization code.
     * @return $this
     */
    public function setPreAuthorizationDate($pre_authorization_date)
    {
        
        $this->pre_authorization_date = $pre_authorization_date;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
