<?php
/**
 * TransactionsFixtureTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use PHPUnit\Framework\TestCase;
use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;
use Swagger\Client\Model\CreditCardInformationModel;
use Swagger\Client\Model\AttributeValueModel;
use Swagger\Client\Api\TransactionsApi;
use Swagger\Client\Api\TransactionFeesApi;
use Swagger\Client\Model\PostTransactionRequestModel;
use Swagger\Client\Model\PostVoidTransactionRequestModel;
use Swagger\Client\Model\GetTransactionFeesResponseModel;
require_once '../../vendor/autoload.php';

/**
 * TransactionsFixtureTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionsFixtureTest extends TestCase
{

    private $transactionsApi;   
    private $transactionFeesApi;
    /**
     * Prepares the environment before running a test.
     */
    public function setUp()
    {
        parent::setUp();     
        $testConfig = parse_ini_file('../../config.ini'); 
		$configuration = new Configuration();        
        $configuration->setHost($testConfig['API_URI']);        
        $keyWithSecret = $testConfig['API_KEY'].":".$testConfig['API_SECRET'];
        $configuration->addDefaultHeader("Authorization", "Basic " .base64_encode($keyWithSecret));       
        
        $apiClient = new ApiClient($configuration);
		
        $this->transactionsApi = new TransactionsApi($apiClient);
        $this->transactionFeesApi = new TransactionFeesApi($apiClient);
    }
    
    /**
     * Cleans up the environment after running a test.
     */
    public function tearDown()
    {
        $this->transactionsApi = null;
        $this->transactionFeesApi = null;
        parent::tearDown();
    }
    
    public function testShould_Successfully_GetTransactionFees_API()
    {
        //Get random amount between 1 and 1000
        $randomAmount = rand(1,1000);  
        print_r($randomAmount);              
        print_r("\r\n");  

        $transactionFeesResponseModel = new GetTransactionFeesResponseModel();
        $transactionFeesResponseModel = $this->transactionFeesApi->transactionFeesGet($randomAmount);
        print_r($transactionFeesResponseModel);
        print_r("\r\n");
        print_r($transactionFeesResponseModel->getAchPayerFee());
        print_r("\r\n");
        print_r($transactionFeesResponseModel->getCreditCardPayerFee());

        $this->assertNotNull($transactionFeesResponseModel);
        $this->assertTrue($transactionFeesResponseModel->getAchPayerFee() != 0);
        $this->assertTrue($transactionFeesResponseModel->getCreditCardPayerFee() != 0);
    }
    
    /**
     * Test case for TransactionsFixture
     *
     * TBD
     *
     */
    public function testShould_Successfully_Process_And_Void_Credit_Card() {	
        
        //Get random amount between 1 and 1000
        $randomAmount = rand(1,1000);          
        
        $postTransactionRequestModel = new PostTransactionRequestModel();
        $postTransactionRequestModel->setPayer("John Smith");
        $postTransactionRequestModel->setEmailAddress("jsmith@example.com");
        $postTransactionRequestModel->setAmount($randomAmount);
        $postTransactionRequestModel->setComments("Sample Comments");
        $postTransactionRequestModel->setSendReceipt(false);  
        $postTransactionRequestModel->setPayerFee($randomAmount * .10 );      
		
		$creditCardInfo = new CreditCardInformationModel();
		$creditCardInfo->setAccountHolder("John Smith");
		$creditCardInfo->setCardNumber("4242424242424242");
		$creditCardInfo->setCvc("123");
		$creditCardInfo->setMonth(12);
		$creditCardInfo->setYear(2021);
		$creditCardInfo->setPostalCode("54321");
		
		$postTransactionRequestModel->setCreditCardInformation($creditCardInfo);
        		
        $postTransactionRequestModel->setAttributeValues(array(
            'phoneNumber' => '512-234-1233', 
            'agentCode' => '213498')
        );
		
        $transactionId = $this->transactionsApi->transactionsPost($postTransactionRequestModel);
        $this->assertTrue($transactionId > 0);

        $transactionResponseModel = $this->transactionsApi->transactionsGet($transactionId);

        $this->assertTrue($transactionResponseModel != null);

        $this->assertSame(count($transactionResponseModel->getAttributeValues()), 2);
        $attribute1 = $transactionResponseModel->getAttributeValues()[0];
        $attribute2 = $transactionResponseModel->getAttributeValues()[1];
        $this->assertSame($attribute1->getParameterName(), "phoneNumber");
        $this->assertSame($attribute1->getValue(), "512-234-1233");
        $this->assertSame($attribute2->getParameterName(), "agentCode");
        $this->assertSame($attribute2->getValue(), "213498");

        $voidTransactionRequestMode = new PostVoidTransactionRequestModel();
        $voidTransactionRequestMode->setSendReceipt(false);

        $statusCode = $this->transactionsApi->transactionsVoid($transactionId, $voidTransactionRequestMode);
        $this->assertSame($statusCode, 200);
    }
}